[project]
name = "my_package"
version = "1.0.0"
description = "Test secondary source"
dependencies = ["requests>=2.28.0,<3.0.0"]
requires-python = ">=3.9.0,<4.0.0"

[[project.authors]]
name = "Dev"
email = "dev@example.com"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[[tool.uv.index]]
name = "private"
url = "https://pypi.example.com/simple/"
priority = "supplemental"
