[project]
name = "my_app"
version = "1.0.0"
description = "Application mode warning"
dependencies = ["requests>=2.28.0,<3.0.0"]
requires-python = ">=3.9,<4.0"

[[project.authors]]
name = "Dev"
email = "dev@example.com"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
